{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "spiffile-operator.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels: {{- include "spiffile-operator.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "spiffile-operator.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 443
      targetPort: webhook
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "spiffile-operator.name" . }}-webhook-selfsigned
  namespace: {{ .Release.Namespace }}
  labels: {{- include "spiffile-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "spiffile-operator.name" . }}-webhook-cert
  namespace: {{ .Release.Namespace }}
  labels: {{- include "spiffile-operator.labels" . | nindent 4 }}
spec:
  secretName: {{ include "spiffile-operator.name" . }}-webhook-server-cert
  dnsNames:
    - {{ include "spiffile-operator.name" . }}-webhook.{{ .Release.Namespace }}.svc
    - {{ include "spiffile-operator.name" . }}-webhook.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ include "spiffile-operator.name" . }}-webhook-selfsigned
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "spiffile-operator.name" . }}-pod-injection
  labels: {{- include "spiffile-operator.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "spiffile-operator.name" . }}-webhook-cert
webhooks:
  - name: inject.spiffile.io
    admissionReviewVersions: ["v1"]
    sideEffects: None
    failurePolicy: {{ .Values.webhook.failurePolicy }}
    namespaceSelector:
      matchLabels:
        spiffile.io/injection: enabled
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
    clientConfig:
      service:
        name: {{ include "spiffile-operator.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: /inject-pod
{{- end }}
